# Generated by Django 5.1.5 on 2025-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_last_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='last_message',
            new_name='lastMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
