# Generated by Django 5.1.5 on 2025-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_last_message_chatroom_lastmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
